server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://192.168.1.39:5432/Lastfm
    username: shicks
    password:
    platform: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

lastfm:
  user: shicks255
  apiKey: