server:
  port: 8686

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 25
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger
    display-request-duration: true
    operations-sorter: "alpha"
    tags-sorter: "alpha"

lastfm:
  user: shicks255
  apiKey:

management:
  endpoints:
    web:
      exposure:
        include: "*"
